<?php
/*------------------------------------------------------------------------
 # SM Facebook - Version 1.0.0
 # Copyright (c) 2014 YouTech Company. All Rights Reserved.
 # @license - Copyrighted Commercial Software
 # Author: YouTech Company
 # Websites: http://www.magentech.com
-------------------------------------------------------------------------*/

$tag_id = 'sm_facebook_' . rand() . time();
if( $this->_getConfig('facebook_type') == 1 ){
	$facebook_html = $this->getActivityFeed();
} elseif( $this->_getConfig('facebook_type') == 2 ){
	$facebook_html = $this->getFanbox();
} elseif( $this->_getConfig('facebook_type') == 3 ){
	$facebook_html = $this->getRecommendations();
}
if (!empty($facebook_html)) {?>
	
	<div id="<?php echo $tag_id; ?>" class="sm-facebook">
        <div class="title-home">
            <h2><?php echo $this->__('Follow Us') ?></h2>
        </div>
		<?php $pretext = $this->_getConfig('pretext');
		if (!empty($pretext)) { ?>
			<div class="pre-text"><?php echo $this->_getConfig('pretext'); ?></div>
		<?php } ?>
		
		<div class="sm-facebook-content">
			<?php echo $facebook_html; ?>
		</div>
		
		<?php $posttext = $this->_getConfig('posttext');
		if (!empty($posttext)) { ?>
			<div class="post-text"><?php echo $this->_getConfig('posttext'); ?></div>
		<?php } ?>
	</div>
	
<?php } else { echo 'Has no item to show!'; } ?>



