<?php
/*------------------------------------------------------------------------
 # SM Basic Products - Version 1.0.0
 # Copyright (c) 2014 YouTech Company. All Rights Reserved.
 # @license - Copyrighted Commercial Software
 # Author: YouTech Company
 # Websites: http://www.magentech.com
-------------------------------------------------------------------------*/
$list = $this->_getProducts();
$helper = Mage::helper('basicproducts/data');
if (!empty($list)) {
    $uniqued = 'sm_basic_products_' . time() . rand();

    $class_respl = 'bs-resp01-' . $this->_getConfig('nb_column1', 6) . ' bs-resp02-' . $this->_getConfig('nb_column2', 4) . ' bs-resp03-' . $this->_getConfig('nb_column3', 2) . ' bs-resp04-' . $this->_getConfig('nb_column4', 1);

    ?>

    <?php if ($this->_getConfig('pretext') != null) { ?>
        <div class="bs-pretext">
            <?php echo $this->_getConfig('pretext'); ?>
        </div>
    <?php } ?>

    <?php if ($this->_getConfig('basicproducts_title_text')) { ?>
        <div class="basicproducts_title_text">
            <?php echo $this->_getConfig('basicproducts_title_text', 'Basic Products Title'); ?>
        </div>
    <?php } ?>

    <div id="<?php echo $uniqued; ?>" class="products-grid sm-basic-products basic-products-menu"><!--<![endif]-->
        <!-- Begin bs-items     -->
        <div class="item bs-items  <?php echo $class_respl; ?> ">
            <?php  $j = 0;
            foreach ($list as $_product) {
					$j++;
                    if($j > 3) {
                        break;
                    }
					$now = date("Y-m-d");
					$newsFrom = substr($_product->getData('news_from_date'), 0, 10);
					$newsTo = substr($_product->getData('news_to_date'), 0, 10);

					$specialprice = $_product->getData('special_price');

					if ($specialprice == '') {
						$store_id = Mage::app()->getStore()->getStoreId();
						$discounted_price = Mage::getResourceModel('catalogrule/rule')->getRulePrice(
							Mage::app()->getLocale()->storeTimeStamp($store_id),
							Mage::app()->getStore($store_id)->getWebsiteId(),
							Mage::getSingleton('customer/session')->getCustomerGroupId(),
							$_product->getId());
						$specialprice = $discounted_price;
					}
                ?>
                <!-- Begin bs-item-cf -->
                <div class="bs-item cf">
                    <!-- Begin bs-item-inner -->
                    <div class="item-inner">
						
                        <?php if ($_product->_image) { ?>
                            <div class="box-image">
                                <a class="product-image" href="<?php echo $_product->link ?>"
                                   title="<?php echo $_product->title; ?>"
                                    <?php echo $helper->parseTarget($this->_getConfig('product_links_target')); ?>
                                    >
                                    <img src="<?php echo $_product->_image; ?>"
                                         title="<?php echo $_product->title; ?>"
                                         alt="<?php echo $_product->title; ?>"
                                        >
										
									<?php if($_product->getThumbnail() != $_product->getSmallImage()) { ?> 
										<img class="second-image" src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->resize(300, 200); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
									<?php } ?>
                                </a>
								
								<?php if ($newsFrom != "" && $now >= $newsFrom && ($now <= $newsTo || $newsTo == "")) { ?>
									<div class="new-item">
										<span class="txt-label"><?php echo $this->__('New') ?></span>
									</div>
								<?php } ?>
									
								<?php if ($specialprice) { ?>
									<div class="sale-item">
										<span class="txt-label"><?php echo $this->__('Sale') ?></span>
									</div>
								<?php } ?>
                            </div>
                        <?php } ?>

                        <!-- Begin bs-content -->
                        <div class="box-info">

                            <?php if ((int)$this->_getConfig('product_title_display', 1)) { ?>
                                <h2 class="product-name">
                                    <a href="<?php echo $_product->link; ?>" title="<?php echo $_product->title; ?>"
                                        <?php echo $helper->parseTarget($this->_getConfig('product_links_target')); ?>
                                        >
                                        <?php echo $helper->truncate($_product->title, $this->_getConfig('product_title_maxlength')); ?>
                                    </a>
                                </h2>
                            <?php } ?>
							
							

                            <?php if ((int)$this->_getConfig('product_description_display', 1) && $helper->_trimEncode($_product->_description) != '') { ?>
                                <div class="bs-description">
                                    <?php echo $_product->_description; ?>
                                </div>
                            <?php } ?>

                            <?php if ($this->_getConfig('cat_title_display') == 1) { ?>
                                <div class="bs-category">
                                    <a href="<?php echo $_product->catlink; ?>"
                                       title="<?php echo $_product->category_title; ?>"
                                        <?php echo $helper->parseTarget($this->_getConfig('product_links_target')); ?>
                                        >
                                        <?php echo 'Category:&nbsp' . $helper->truncate($_product->category_title, $this->_getConfig('category_title_max_characs', 25)); ?>
                                    </a>
                                </div>
                            <?php } ?>

                            <?php if ($this->_getConfig('item_date_display') == 1) { ?>
                                <div class="bs-date">
                                    <?php echo $_product->created_at; ?>
                                </div>
                            <?php } ?>

                            



                            <?php if ($this->_getConfig('product_readmore_display') == 1) { ?>
                                <div class="bs-detail">
                                    <a href="<?php echo $_product->link ?>"
                                       title="<?php echo $_product->title; ?>"
                                        <?php echo $helper->parseTarget($this->_getConfig('product_links_target')); ?>
                                        >
                                        <?php echo $this->_getConfig('product_readmore_text', 'Details'); ?>
                                    </a>
                                </div>
                            <?php } ?>
							
							
							<?php if ($this->_getConfig('product_source') != 'media') { ?>
                                <?php if ((int)$this->_getConfig('product_reviews_count', 1)) { ?>
                                    <div class="bs-review">
                                        <?php
                                        $this->addReviewSummaryTemplate('sm', 'sm/basicproducts/default_summary.phtml');
                                        echo $this->getReviewsSummaryHtml($_product, 'sm', true);
                                        ?>
                                    </div>
                                <?php } ?>

                                <?php if ((int)$this->_getConfig('product_price_display', 1)) { ?>
                                    <div class="bs-price">
                                        <div class="sale-price">
                                            <?php echo $this->getPriceHtml($_product, true); ?>
                                        </div>
                                    </div>
                                <?php } ?>

								<div class="actions">
									<?php if ((int)$this->_getConfig('product_addcart_display', 1)) : ?>
										<?php if ($_product->isSaleable()): ?>

												<button type="button" title="<?php echo $this->__('Add to Cart') ?>"
														class="button btn-cart"
														onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
													<span><span><?php echo $this->__('Add to Cart') ?></span></span>
												</button>

										<?php else: ?>
											<p class="availability out-of-stock">
														<span>
															<?php echo $this->__('Out of stock') ?>
														</span>
											</p>
										<?php endif;
									endif;
									if ((int)$this->_getConfig('product_addwishlist_display', 1) || (int)$this->_getConfig('product_addcompare_display', 1)) :?>
										<ul class="add-to-links">
											<?php if ($this->helper('wishlist')->isAllow() && (int)$this->_getConfig('product_addwishlist_display', 1)) : ?>
												<li>
													<a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>"
													   class="link-wishlist"><?php echo $this->__('Wishlist') ?></a>
												</li>
											<?php endif; ?>
											<?php if ($_compareUrl = $this->getAddToCompareUrl($_product) && (int)$this->_getConfig('product_addcompare_display', 1)): ?>
												<li>
													<span class="separator">|</span>
													<a
														href="<?php echo $_compareUrl ?>"
														class="link-compare"><?php echo $this->__('Compare') ?>
													</a>
												</li>
											<?php endif; ?>
										</ul>
									<?php endif; ?>

								</div>
								
                            <?php } ?>
							
                        </div>
                        <!-- End bs-content -->
                    </div>
                    <!-- End bs-item-inner -->
                </div><!-- End bs-item-cf -->
            <?php } ?>
        </div>
        <!-- End bs-items -->
    </div><!-- End Sm-basic-products -->
    <?php if ($this->_getConfig('posttext') != null) { ?>
        <div class="bs-posttext">
            <?php echo $this->_getConfig('posttext'); ?>
        </div>
    <?php } ?>


<?php
} else {
    echo 'Has no content to show!';
}?>