<?php
/*------------------------------------------------------------------------
 # SM Deal - Version 1.0.0
 # Copyright (c) 2014 YouTech Company. All Rights Reserved.
 # @license - Copyrighted Commercial Software
 # Author: YouTech Company
 # Websites: http://www.magentech.com
-------------------------------------------------------------------------*/?>

<script type="text/javascript">
//<![CDATA[
data = new Date(2013,10,26,12,00,00);
var listdeal = [];
function CountDown(date,id){
	dateNow = new Date();
	amount = date.getTime() - dateNow.getTime();
	delete dateNow;
	if(amount < 0){
		document.getElementById(id).innerHTML="Now!";
	} else{
		days=0;hours=0;mins=0;secs=0;out="";
		amount = Math.floor(amount/1000);
		days=Math.floor(amount/86400);
		amount=amount%86400;
		hours=Math.floor(amount/3600);
		amount=amount%3600;
		mins=Math.floor(amount/60);
		amount=amount%60;
		secs=Math.floor(amount);
		if(days != 0){out += "<div class='time-item time-day'>" + "<div class='num-time'>" + days + "</div>" +" <div class='name-time'>"+((days==1)?"Day":"Days") + "</div>"+"</div> ";}
		if(hours != 0){out += "<div class='time-item time-hour'>" + "<div class='num-time'>" + hours + "</div>" +" <div class='name-time'>"+((hours==1)?"Hour":"Hours") + "</div>"+"</div> ";}
		out += "<div class='time-item time-min'>" + "<div class='num-time'>" + mins + "</div>" +" <div class='name-time'>"+((mins==1)?"Min":"Mins") + "</div>"+"</div> ";
		out += "<div class='time-item time-sec'>" + "<div class='num-time'>" + secs + "</div>" +" <div class='name-time'>"+((secs==1)?"Sec":"Secs") + "</div>"+"</div> ";
		out = out.substr(0,out.length-2);
		document.getElementById(id).innerHTML=out;
		setTimeout(function(){CountDown(date,id)}, 1000);
	}
}
//]]>
</script>

<?php 
$config = Mage::helper('restaurant/config');

$effect_style = $config->getProductListing('effect_style');
$display_nav = $config->getProductListing('show_nav');
$display_dot = $config->getProductListing('show_dot');

$list = $this->_getProducts();
$helper = Mage::helper('deal/data');
if (!empty($list)) {
	$uniqued = 'sm_deal_' . time() . rand();
	
	$nb_column1 = $this->_getConfig('nb_column1', 6);
	$nb_column2 = $this->_getConfig('nb_column2', 4);
	$nb_column3 = $this->_getConfig('nb_column3', 2);
	$nb_column4 = $this->_getConfig('nb_column4', 1);

?>

<div id="deals" class="overflow-slider slider-deal-wrapper">
	<?php if( $this->_getConfig('deal_title_text') ){ ?>
		<div class="title-home wow fadeIn"><h2><?php echo $this->_getConfig('deal_title_text','Deal Title'); ?></h2></div>
	<?php } ?>
	<?php if ( $this->_getConfig('pretext') != null ) { ?>
		<div class="deal-pretext wow fadeIn">
			<?php echo $this->_getConfig('pretext'); ?>
		</div>
	<?php } ?>

	<div id="<?php echo $uniqued; ?>" class="margin-slider wow fadeIn">
		<div class="products-grid deal-slider">
			<?php  
			$j = 0;
			$_limit = (int)$this->_getConfig('product_limitation', 5);		
			if ( $_limit <= 0 ){
				$_limit = count($list);
			}
			
			$product_model = Mage::getModel('catalog/product');
			
			foreach ($list as $_product) {

				$now = date("Y-m-d");
				$newsFrom = substr($_product->getData('news_from_date'), 0, 10);
				$newsTo = substr($_product->getData('news_to_date'), 0, 10);
				
				$specialPriceFromDate = $_product->special_from_date;

				$specialPriceToDate = $_product->special_to_date;

				$today =  time();
				$dayDate  = Mage::app()->getLocale()->date()->toString(Varien_Date::DATETIME_INTERNAL_FORMAT);	
			
			if ($specialPriceFromDate && $specialPriceToDate){
				if( $today >= strtotime( $specialPriceFromDate) && $today <= strtotime($specialPriceToDate) || $today >= strtotime( $specialPriceFromDate) && is_null($specialPriceToDate) ){
					$specialprice = $_product->special_price;					
					
					$j++;
					if( $j <= $_limit && $specialprice){
					?>			
					<div class="item">
						<div class="item-inner">
							
							<?php if ( $_product->_image && $this->_getConfig('product_image_display') ) { ?>
							<div class="box-image">
								
								
								<?php
									$url_product = $_product->link;
								?>
								
								<?php if($effect_style == 'default'){?>
								<div class="effect-default">
									<a class="product-image" href="<?php echo $url_product; ?>" title="<?php echo $_product->title; ?>">
										<img src="<?php echo $_product->_image; ?>" title="<?php echo $_product->title; ?>" alt="<?php echo $_product->title; ?>" >
									</a>
								</div>
								<?php } else if($effect_style == 'thumbs'){?>
								<div class="effect-thumbs">
									<a class="product-image" href="<?php echo $url_product; ?>" title="<?php echo $_product->title; ?>" >
										<img src="<?php echo $_product->_image; ?>" title="<?php echo $_product->title; ?>" alt="<?php echo $_product->title; ?>" >
										<?php if($_product->getThumbnail() != $_product->getSmallImage()) { ?> 
											<img class="second-image" src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->resize(420 ,315); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
										<?php } ?>
									</a>
								</div>
								<?php } else if($effect_style == 'slider'){?>
								<div class="effect-slider">
									<a class="product-image" href="<?php echo $url_product; ?>" title="<?php echo $_product->title; ?>" >
										<img src="<?php echo $_product->_image; ?>" title="<?php echo $_product->title; ?>" alt="<?php echo $_product->title; ?>" >
									</a>
									
									<div class="image-slider-product">
										<div class="deal-img-slider">
											<?php $_media = Mage::getModel('catalog/product')->load($_product->getId())->getMediaGalleryImages() ?>
											<?php foreach($_media as $_img): ?>
												<div class="item_deal">
													<a href="<?php echo $url_product ?>" title="<?php echo $_product->title;?>">
														<img  src="<?php echo $this->helper('catalog/image')->init($_product, 'image', $_img->getFile())->resize(420 ,315); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true); ?>" />
													</a>
												</div>
											<?php endforeach; ?>
										</div>
									</div>
									
									
								</div>
								<?php } ?>

                                <?php if ($newsFrom != "" && $now >= $newsFrom && ($now <= $newsTo || $newsTo == "")) { ?>
                                    <div class="new-item">
                                        <span class="txt-label"><?php echo $this->__('New') ?></span>
                                    </div>
                                <?php } ?>

                                <?php if ($specialprice) { ?>
                                    <div class="sale-item">
                                        <span class="txt-label"><?php echo $this->__('Sale') ?></span>
                                    </div>
                                <?php } ?>

                                <div class="timer-product">
                                    <div id="product_time_<?php echo $j;?>" class="time-count"></div>
                                </div>
                                <div class="actions">
                                    <?php if ((int)$this->_getConfig('product_addcart_display', 1)) : ?>
                                        <?php if ($_product->isSaleable()): ?>
                                            <button type="button" title="<?php echo $this->__('Add to Cart') ?>"
                                                    class="button btn-cart"
                                                    onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
                                                <span><span><?php echo $this->__('Add to Cart') ?></span></span>
                                            </button>
                                        <?php else: ?>
                                            <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                        <?php endif;
                                    endif; ?>

                                    <?php if ((int)$this->_getConfig('product_addwishlist_display', 1) || (int)$this->_getConfig('product_addcompare_display', 1)) :?>
                                        <ul class="add-to-links">
                                            <?php if ($this->helper('wishlist')->isAllow() && (int)$this->_getConfig('product_addwishlist_display', 1)) : ?>
                                                <li>
                                                    <a title="<?php echo $this->__('Add to Wishlist') ?>" href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>"
                                                       class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a>
                                                </li>
                                            <?php endif; ?>
                                            <?php if ((int)$this->_getConfig('product_addcompare_display', 1)) { ?>
                                                <?php if ($_compareUrl = $this->getAddToCompareUrl($_product)) { ?>
                                                    <li>
                                                        <span class="separator">|</span>
                                                        <a
                                                            href="<?php echo $_compareUrl ?>"
                                                            title="<?php echo $this->__('Add to Compare') ?>"
                                                            class="link-compare"><?php echo $this->__('Add to Compare') ?>
                                                        </a>
                                                    </li>
                                            <?php } ?>
                                        <?php } ?>
                                        </ul>
                                    <?php endif; ?>
                                </div>
								<?php if ($newsFrom != "" && $now >= $newsFrom && ($now <= $newsTo || $newsTo == "")) { ?>
									<div class="new-item">
										<span class="txt-label"><?php echo $this->__('New') ?></span>
									</div>
								<?php } ?>
							</div>
							<?php } ?>
							
							<div class="box-info">
                                <div class="item-left f-left a-left">
                                    <?php if( (int)$this->_getConfig('product_title_display',1) ) { ?>
                                        <h2 class="product-name">
                                            <a href="<?php echo $_product->link;?>" title="<?php echo $_product->title; ?>"
                                                <?php echo $helper->parseTarget($this->_getConfig('product_links_target'));?>
                                                >
                                                <?php echo $helper->truncate($_product->title,$this->_getConfig('product_title_maxlength'));?>
                                            </a>
                                        </h2>
                                    <?php } ?>

                                    <?php if ( (int)$this->_getConfig('product_reviews_count', 1) ) { ?>
                                        <?php echo $this->getReviewsSummaryHtml($_product, 'short'); ?>
                                    <?php } ?>
                                </div>

                                <div class="item-right f-right a-right">
                                    <?php if ((int)$this->_getConfig('product_price_display', 1)) { ?>
                                        <?php echo $this->getPriceHtml($_product, true); ?>
                                    <?php } ?>
                                </div>

								<?php if ( (int)$this->_getConfig('product_description_display', 1) ) { ?>
									<div class="deal-description">
										<?php echo $_product->_description; ?>
									</div>
								<?php } ?>

								<?php if ($this->_getConfig('item_date_display') == 1) { ?>
									<div class="deal-date">
										<?php  echo  $_product->created_at; ?>
									</div>
								<?php } ?>

								<?php if ($this->_getConfig('product_readmore_display') == 1) { ?>
									<div class="deal-detail">
										<a href="<?php echo $_product->link ?>"
										   title="<?php echo $_product->title; ?>"
											<?php echo $helper->parseTarget($this->_getConfig('product_links_target'));?>
											>
											<?php echo $this->_getConfig('product_readmore_text','Details'); ?>
										</a>
									</div>
								<?php } ?>
								

								
								<script type="text/javascript">
								//<![CDATA[
									listdeal.push('product_time_<?php echo $j."&&||&&".date("Y/m/d", strtotime($specialPriceToDate));?>') ;
								//]]>
								</script>	


								
							</div>




						</div>
					</div>

					<?php }
				}
				} ?>
			<?php } ?>
		</div>
	</div>
</div>
<?php if ($this->_getConfig('posttext') != null) { ?>
	<div class="deal-posttext"><?php echo $this->_getConfig('posttext'); ?></div>
<?php } ?>

<script type="text/javascript">
//<![CDATA[
window.onload=function(){
	if(listdeal.length > 0){
		for(i=0;i<listdeal.length;i++)
		{
			var arr = listdeal[i].split("&&||&&"); 
			var data = new Date(arr[1]);
			CountDown(data, arr[0]);
		}	
	}
};
//]]>
</script>
<script>
		jQuery(document).ready(function($) {
			var owl_deal = $(".deal-slider");
			owl_deal.owlCarousel({
				responsive:{
					0:{
						items:1
					},
					480:{
						items:<?php echo $nb_column4;?>
					},
					768:{
						items:<?php echo $nb_column3;?>
					},
					992:{
						items:<?php echo $nb_column2;?>
					},
					1200:{
						items:<?php echo $nb_column1;?>
					}
				},

				autoplay:false,
				loop:false,
				/* stagePadding:1, */
				nav : true, // Show next and prev buttons
				dots: false,
				autoplaySpeed : 500,
				navSpeed : 500,
				dotsSpeed : 500,
				autoplayHoverPause: true,
				margin:30

			});

			//IMAGE SLIDER PRODUCT

			$(".deal-img-slider").lightSlider({
				loop: false,
				vertical:false,
				slideMargin: 0,
                autoWidth: true,
				item: 1,

				<?php if($display_nav){?>
					controls : true, // Show next and prev buttons
				<?php } else { ?>
					controls : false,
				<?php } ?>

				<?php if($display_dot){?>
					pager: true,
				<?php } else {?>
					pager: false,
				<?php } ?>
			});

		});	
</script>	
<?php } else { echo $this->__('Has no content to show!'); }; ?>