<?php
/*------------------------------------------------------------------------
 # SM Listing Tabs - Version 2.0.0
 # Copyright (c) 2014 YouTech Company. All Rights Reserved.
 # @license - Copyrighted Commercial Software
 # Author: YouTech Company
 # Websites: http://www.magentech.com
-------------------------------------------------------------------------*/
$helper = Mage::helper('listingtabs/data');
$list = $this->_getList();

$device1 = $this->_getConfig('nbi_column1', 4);
$device2 = $this->_getConfig('nbi_column2', 3);
$device3 = $this->_getConfig('nbi_column3', 2);
$device4 = $this->_getConfig('nbi_column4', 1);
if (!empty($list)) {

    $import_str = "";
    $jsHelper = Mage::helper('core/js');
    // jquery has not added yet
    if (!defined('MAGENTECH_JQUERY') && (int)$this->_getConfig('include_jquery')) {
        // if module allowed jquery.
        $import_str .= $jsHelper->includeSkinScript('sm/listingtabs/js/jquery-1.8.2.min.js');
        $import_str .= $jsHelper->includeSkinScript('sm/listingtabs/js/jquery-noconflict.js');
        define('MAGENTECH_JQUERY', 1);
    }
    echo $import_str;


    $module_id = $this->_moduleID();
    $tag_id = 'sm_listing_tabs_' . rand() . time();
    $class_ltabs = 'ltabs00-' . $this->_getConfig('nbi_column1', 4) . ' ltabs01-' . $this->_getConfig('nbi_column1', 3) . ' ltabs02-' . $this->_getConfig('nbi_column2', 3) . ' ltabs03-' . $this->_getConfig('nbi-column3', 2) . ' ltabs04-' . $this->_getConfig('nbi-column4', 1)
    ?>
	
	<div id="listing-tab-menu1" class="sm-listing-tab-menu">
		<div id="<?php echo $tag_id; ?>" class="sj-listing-tabs first-load">
			<div class="ltabs-wrap row">
				<div class="ltabs-tabs-container col-lg-2" data-delay="<?php //echo $this->_getConfig('delay', 300); ?>"
					 data-duration="<?php //echo $this->_getConfig('duration', 600); ?>"
					 data-effect="<?php //echo $this->_getConfig('effect'); ?>"
					 data-ajaxurl="<?php echo Mage::getBaseUrl() . 'listingtabs/index/ajax'; ?>"
					 data-modid="<?php echo $tag_id; ?>">
					<!--Begin Tabs-->
					<?php include('default_tabs.phtml'); ?>
				</div>
				<!-- End Tabs-->

				<div class="ltabs-items-container col-lg-10"><!--Begin Items-->
                    <?php if ($this->_getConfig('listingtabs_title_text')):  ?>
                        <div class="tab-listing-title">
                            <strong><?php echo $this->_getConfig('listingtabs_title_text', 'Tab Listing'); ?></strong>
                        </div>
                    <?php endif; ?>
					<?php foreach ($list as $items) {
						$child_items = isset($items->child) ? $items->child : '';
						$cls_device = $class_ltabs;
						$cls_animate = $this->_getConfig('effect');
						$cls = (isset($items->sel) && $items->sel == "sel") ? ' ltabs-items-selected ltabs-items-loaded' : '';
						$cls .= ($items->id == "*") ? ' items-category-all' : ' items-category-' . $items->id;
						
						$cl_slider = $items->id;
						?>

						<div class="products-grid">
							<div class="item ltabs-items listing-<?php echo $cl_slider;?> listing-<?php echo $tag_id;?> <?php echo $cls; ?>">
								<div class="ltabs-items-inner <?php echo $cls_device . ' ';
								echo $cls_animate; ?>">
									<?php if (!empty($child_items)) {
										include('default_items.php'); ?>
										<script>
											jQuery.noConflict()
											var slider_listing = jQuery(".slider-listing");
											slider_listing.owlCarousel({
												responsive:{
													0:{
														items:<?php echo $device4?>
													},
													480:{
														items:<?php echo $device3?>
													},
													768:{
														items:<?php echo $device2?>
													},
													992:{
														items:<?php echo $device2?>
													},
													1200:{
														items:<?php echo $device1?>
													}
												},
													
												autoplay:false,
												loop:false,
												nav : true, // Show next and prev buttons
												dots: false,
												autoplaySpeed : 500,
												navSpeed : 500,
												dotsSpeed : 500,
												autoplayHoverPause: true,
												margin:30
											});	 

										</script>
										
										
									<?php } else {
										?>
										<div class="ltabs-loading"></div>
									<?php } ?>
								</div>
							</div>
						</div>
					<?php } ?>
				</div>
				<!--End Items-->
			</div>
		</div>
	</div>
    <?php include('default_js_menu.phtml'); ?>
<?php
} else {
    echo 'Has no item to show!';
} ?>





