<?php
$uq = rand().time();
?>

<div class="product-custom-tabs col-xs-12">
    <div class="custom-tab-head">
        <ul class="nav-tabs gfont">
            <?php $active = ' active'; ?>
            <?php foreach ($this->getChildGroup('custom_tabs', 'getChildHtml') as $alias => $html):?>
                <li class="<?php echo $active;?>">
                    <a data-toggle="tab" href="#sns_custom_tab_<?php echo "{$alias}" . $uq; ?>">
                        <?php
                        if ($cat_id = $this->getChildData($alias, 'product_category')):
                            $title = Mage::getModel('catalog/category')->load($cat_id)->getName();
                            echo $this->escapeHtml($title);
                        else :
                            echo ucfirst("{$alias}");
                        endif;
                        ?>
                    </a>
                </li>
                <?php $active = ''; ?>
            <?php endforeach;?>
        </ul>
    </div>

    <div class="tab-content">
        <?php $active = ' active in'; ?>
        <?php foreach ($this->getChildGroup('custom_tabs', 'getChildHtml') as $alias => $html):?>
            <div id="sns_custom_tab_<?php echo "{$alias}" . $uq; ?>" class="tab-pane<?php echo $active;?> fade">
                <div class="collateral-box">
                    <?php echo $html ?>
                </div>
            </div>
            <?php $active = ''; ?>
        <?php endforeach;?>
    </div>
</div>
<script>
    jQuery(document).ready(function($) {
        $('.product-custom-tabs .nav-tabs li > a').on('hover', function(e){
            e.preventDefault();
           $(this).trigger('click');
//            return false;
        });
    });
</script>