<?php
/*------------------------------------------------------------------------
 # SM Mega Menu - Version 1.1
 # Copyright (c) 2013 YouTech Company. All Rights Reserved.
 # @license - Copyrighted Commercial Software
 # Author: YouTech Company
 # Websites: http://www.magentech.com
-------------------------------------------------------------------------*/

include_once 'Mobile_Detect.php';
$prefix = Sm_Megamenu_Model_System_Config_Source_Html::PREFIX;
$smarthelper= Mage::helper('megamenu/utils');
$itemsStartLv = $this->getItems();
$config = $this->getConfigObject();
$uq = uniqid($prefix.'menu');
$detect = new Mobile_Detect();
if($config['theme']==Sm_Megamenu_Model_System_Config_Source_ListTheme::HORIZONTAL){
$theme = 'horizontal';
}
if($config['theme']==Sm_Megamenu_Model_System_Config_Source_ListTheme::VERTICAL){
$theme = 'vertical'; 
}
$instance	= rand().time();
echo $this->getScriptTags();
global $var_yttheme;
$theme_config = Mage::helper('restaurant/config');
$menu_style = $theme_config->getGeneral('menu_styles');
$firstClassName = "";
?>
<?php if(count($itemsStartLv)):?>
	<?php include dirname(__FILE__) . '/js/add_js_by_effect.phtml'; ?>
	<?php //include dirname(__FILE__) . '/css/add_css_by_theme.phtml'; ?>
	<div class="megamenu-left megamenu-left-style-1">
		<?php if (!empty($config['title'])): ?>
		<div class="<?php echo $prefix; ?>block-title"><?php echo $config['title']; ?></div>
		<?php endif; ?>

        <?php //if( $menu_style == '1' ): ?>
        <?php if( $var_yttheme->getParam('menustyle')=='mega' ): ?>

            <div class="<?php echo $prefix; ?>wrapper_<?php echo $theme?>_menu sambar" id="<?php echo $uq; ?>" data-sam="<?php echo $instance; ?>">
                <div class="sambar-inner">
                    <ul class="<?php if ( !$detect->isMobile() && !$detect->isTablet() ) { echo "sm-megamenu-hover";}?> <?php echo $prefix; ?>menu <?php echo $prefix; ?>menu_black" data-jsapi="on">
                    <?php 	foreach($itemsStartLv as $itemStartLv){ ?>
                                <li class="<?php if($itemStartLv->getCustomClass()){ echo 'parent-'.$itemStartLv->getCustomClass();}?><?php echo 'class'?><?php if( $config['effect'] == 1 || $config['effect'] == 2 ){ echo ' other-toggle ';}?>
                                <?php echo $prefix; ?>lv1 <?php echo (!$this->isLeaf($itemStartLv) OR ($this->isLeaf($itemStartLv) AND $this->hasConntentType($itemStartLv)))?$prefix.'drop parent':$prefix.'nodrop'?>  <?php echo ($this->isAlignRight($itemStartLv))?$prefix.'right':''?> <?php echo ($this->isActived($itemStartLv))?$prefix.'actived':'' ?>">
                                                        <a class="<?php echo $prefix; ?>head <?php echo (!$this->isLeaf($itemStartLv) OR ($this->isLeaf($itemStartLv) AND $this->hasConntentType($itemStartLv)))?$prefix.'drop':$prefix.'nodrop'?> <?php echo ($this->isActived($itemStartLv))?$prefix.'actived'.' '.$prefix.'top_actived':'' ?>" href="<?php echo ($this->hasLinkType($itemStartLv))?$this->getLinkOfType($itemStartLv):'javascript:void(0)'?>" <?php echo ($this->hasLinkType($itemStartLv))?$smarthelper->getTargetAttr($itemStartLv->getTarget()):'' ?> id="<?php echo $prefix.$itemStartLv->getId()?>">

                                                            <span class="icon-first <?php if($itemStartLv->getCustomClass()){ echo $itemStartLv->getCustomClass();}?>"></span>

                                                            <span class="<?php echo $prefix; ?>title"><?php echo $itemStartLv->getTitle() ?></span>

                                                            <?php if($this->hasIcon($itemStartLv)) {	?>
                                                            <span class="item-icon"><img alt="icon item" src="<?php echo $this->filterImage($itemStartLv);?>" /></span>
                                                            <span style="" class="<?php echo $prefix; ?>icon <?php if(!$itemStartLv->getDescription()){echo $prefix.'nodesc';}?>">
                                                            <?php }else{	?>
                                                            <span class="<?php echo $prefix; ?>icon <?php if(!$itemStartLv->getDescription()){echo $prefix.'nodesc';}?>">
                                                            <?php } ?>

                                                            <?php if($itemStartLv->getDescription()):?>
                                                                <span class="<?php echo $prefix; ?>description"><?php echo $itemStartLv->getDescription() ?>&nbsp;</span>
                                                            <?php endif?>
                                                            <?php //if($this->hasIcon($itemStartLv)) {	?>
                                                            </span>
                                                            <?php //}	?>
                                                        </a>
                                <?php $childItems = Mage::helper('megamenu')->getChildsDirectlyByItem($itemStartLv);?>
                                <?php 	if($this->isLeaf($itemStartLv) OR !count($childItems->getItems())){ 	?>
                                            <?php 	if($this->hasConntentType($itemStartLv)){	?>
                                                        <div class="<?php echo $prefix; ?>dropdown_<?php echo $itemStartLv->getColsNb()?><?php if($itemStartLv->getColsNb()>1){ ?>columns<?php }else{ ?>column<?php } ?> <?php echo ($this->isAlignRight($itemStartLv))?$prefix.'align_right':''?>
                                                        <?php echo ($this->isActived($itemStartLv))?$prefix.'actived':'' ?>" >
                                                            <?php if($itemStartLv->getShowTitle()==Sm_Megamenu_Model_System_Config_Source_Status::STATUS_ENABLED){	?>
                                                            <div class="<?php echo $prefix; ?>title"><span><?php echo $itemStartLv->getTitle()?></span></div>
                                                            <?php } ?>
                                                            <div class="<?php echo $prefix; ?>content"><?php echo $this->getContentType($itemStartLv) ?></div>
                                                        </div>
                                            <?php 	}	?>
                                <?php 		continue;
                                        }	?>
                                    <?php
                                    if($itemStartLv->getColsNb()>1){
                                        $divClassName = 'sm-megamenu-child ' .$prefix.'dropdown_'.$itemStartLv->getColsNb().'columns ';
                                    }
                                    else{
                                        $divClassName = $prefix.'dropdown_'.$itemStartLv->getColsNb().'column ';
                                    }
                                        if($this->isAlignRight($itemStartLv)){
                                            $divClassName .= $prefix.'align_right';
                                        }
                                        /*if($this->isFlyLeft($itemStartLv)){
                                            $divClassName .= " ".$prefix.'fly_left_wrap';
                                        }*/
                                    ?>
                                    <?php //var_dump($divClassName); ?>
                                <?php 	if($itemStartLv->getDepth()+1 <= $config['end_level']){
                                    //var_dump(get_class($this));
                                ?>
                                                        <div class="<?php echo $divClassName.' '.$firstClassName?>">
                                                            <?php echo $this->getItemHtml($itemStartLv, true);	 ?>
                                                        </div>
                                <?php 	} ?>
                                </li>
                    <?php	}	?>
                    </ul>
                </div>
            </div>

        <?php else: ?>
            <?php echo $this->getLayout()->createBlock('page/html_topmenu')->setTemplate('page/html/topmenu1.phtml')->toHtml() ?>
        <?php endif; ?>

    </div>
	<!--End Module-->
<script type="text/javascript">

</script>

<script type="text/javascript">
// <![CDATA[ 
	jQuery(document).ready(function($){
		$( ".sm_megamenu_wrapper_vertical_menu .sm_megamenu_menu > li" ).has( "div" ).addClass('parent-child');

        $($('.sm_megamenu_block-title').before()).click(function(){
            if(!$(this).parent().hasClass('active')) {
                $(this).parent().addClass('active').animate({
                    'left':'0px'
                }, 300);
                $('.cmspage1 .header-container.header-style-1, .cmspage1 .main-container, .cmspage1 .footer-container.footer-style-1').addClass('move').animate({
                    'left':'283px'
                }, 300);
            }
            else {
                $(this).parent().removeClass('active').animate({
                    'left':'-283px'
                }, 300);
                $('.cmspage1 .header-container.header-style-1, .cmspage1 .main-container, .cmspage1 .footer-container.footer-style-1').removeClass('move').animate({
                    'left':'0px'
                }, 300);
            }

        });
	});
// ]]> 
</script>
<?php else: ?>
<p class="note-msg"><?php echo $this->__('There are no items matching the selection.') ?></p>
<?php endif; ?>

	



