<?php
/*------------------------------------------------------------------------
 # Copyright (c) 2015 YouTech Company. All Rights Reserved.
 # @license - Copyrighted Commercial Software
 # Author: YouTech Company
 # Websites: http://www.magentech.com
-------------------------------------------------------------------------*/

global $var_yttheme; 
$config = Mage::helper('restaurant/config');
?>
<div id="cpanel_wrapper">
	<div class="cpanel-head">
		<span>Theme setting</span>
		<div class="action cpanel-reset">
			<a class="btn" href="#" onclick="javascript: onCPResetDefault(TMPL_COOKIE);">Reset</a>
		</div>		
	</div>
	<div class="cpanel-content">
		<!--Theme-->
        <div class="item-cpanel-group cpanel-theme-color">
            <div class="item-cpanel-heading">Theme Color</div>
        	<div class="item-cpanel-theme">
                <div class="item-cpanel-inner clearfix">
					<div class="color-theme">
						<a href="<?php echo $this->getUrl('?___store=default&amp;___from_store=default')?>" title="Red" class="theme-color red<?php echo ($config->getGeneral('theme_color')=='red')?' active':'';?>">Red</a>
                        <a href="<?php echo $this->getUrl('?___store=french&amp;___from_store=default')?>" title="Dark Red" class="theme-color brown<?php echo ($config->getGeneral('theme_color')=='brown')?' active':'';?>">Dark Red</a>
                        <a href="<?php echo $this->getUrl('?___store=german&amp;___from_store=default')?>" title="Green" class="theme-color green<?php echo ($config->getGeneral('theme_color')=='green')?' active':'';?>">Green</a>
                        <a href="<?php echo $this->getUrl('?___store=argentina&amp;___from_store=default')?>" title="Yellow" class="theme-color yellow<?php echo ($config->getGeneral('theme_color')=='orange')?' active':'';?>">Yellow</a>
					</div>
				</div>
			</div>
        </div>
		<!-- Menu -->
		<div class="item-cpanel-group cpanel-menu">
			<div class="item-cpanel-heading">Menu style</div>
			<div class="item-cpanel-menu">
				<div class="item-cpanel-inner clearfix">
					<select onchange="javascript: onCPApply();" name="ytcpanel_menustyle" class="cp_select">
						<option value="mega" <?php echo ($var_yttheme->getParam('menustyle')=='mega')?' selected="selected"':'';?>>Mega</option>
						<option value="css" <?php echo ($var_yttheme->getParam('menustyle')=='css')?' selected="selected"':'';?>>Css</option>
					</select>
				</div>
			</div>
		</div>
	</div>
	<div id="cpanel_btn" class="normal">
		<i class="fa fa-hand-o-left"></i>
	</div>
</div>
<script type="text/javascript">
	jQuery(document).ready(function($){
		$('.theme-color').click(function(){
			$($(this).parent().find('.active')).removeClass('active'); $(this).addClass('active');
		});
	});
</script>
