<div class="sm_megamenu_wrapper_horizontal_menu1">
    <ul>
        <li class="sm_megamenu_lv11">
            <a href="#home"><?php echo $this->__('Home'); ?></a>
        </li> <li class="sm_megamenu_lv11">
            <a href="#our-menu"><?php echo $this->__('Our Menu'); ?></a>
        </li> <li class="sm_megamenu_lv11">
            <a href="#history"><?php echo $this->__('History'); ?></a>
        </li> <li class="sm_megamenu_lv11">
            <a href="#deals"><?php echo $this->__('Deals'); ?></a>
        </li> <li class="sm_megamenu_lv11">
            <a href="#testimonial"><?php echo $this->__('Testimonials'); ?></a>
        </li> <li class="sm_megamenu_lv11">
            <a href="#blog"><?php echo $this->__('Blog'); ?></a>
        </li> <li class="sm_megamenu_lv11">
            <a href="#contact-us"><?php echo $this->__('Contact us'); ?></a>
    </ul>
</div>
<script>
    jQuery(document).ready(function ($) {
//        var cookie_value;
//    $(window).load(function(event) {
//        if($.cookie('itemMenu_active') !== 'false') {
////            window.location.href = homepage_add + $.cookie('itemMenu_active');
//            window.location.hash = $.cookie('itemMenu_active');
//            $('html,body').animate({scrollTop: $(window).scrollTop() - 330}, 1000);
//        }
//        Home();
//    });
//    function Home() {
//
//        $('.cmspage1 .sm_megamenu_wrapper_horizontal_menu1 ul li > a').on('click', function(e) {
//            var attr = $(this).attr('href');
//
//            if($(this).parents().find('body').hasClass('cms-home')) {
//                $('html, body').animate({scrollTop: $(this.hash).offset().top - 5}, 1000);
//                return false;
//            }
//            else {
//                $.cookie('itemMenu_active', attr, { expires: 1});
//                window.location.href = homepage_add;
//            }
//
//        });
//    }
    });
</script>