<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Blog
 * @version    1.3.6
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?>
<?php if ($posts = $this->getRecent()): ?>
    <div id="blog" class="latest-post-block">
        <div class="title-home wow fadeIn">
            <h2><?php echo $this->__('Our Blog') ?></h2>
        </div>
        <div class="pre-text wow fadeIn">
            <?php echo $this->__('Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam iaculis egestas laoreet') ?>
        </div>
        <div class="content-latest-post wow fadeIn">
            <div class="slider-post">
                <?php $i = 0; foreach ($posts as $post): $i++;?>
                    <div class="item">
                        <div class="img-post">
                            <?php
                            $pattern = "/<img .+\/>/";
                            $subject = $post->getShortContent();
                            $result = preg_match( $pattern, $subject , $matches , PREG_OFFSET_CAPTURE );
                            $matched =$matches[0];
                            $first_img=$matched[0];
                            //print_r($first_img);
                            ?>

                            <a class="img-link" title="<?php echo $post->getTitle(); ?>" href="<?php echo $post->getAddress(); ?>" ><?php echo $first_img;?></a>
                        </div>

                        <div class="info-post">
                            <div class="title-latest-post">
                                <h2><a title="<?php echo $post->getTitle(); ?>" href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a></h2>
                                <div class="date-post">
                                    <?php $date_create = $post->getCreatedTime();
                                    $date_create = date("j F Y", strtotime($date_create));
                                    ?>
                                    <?php echo $date_create;?>
<!--                                    <div class="day-post">-->
<!--                                        --><?php
//                                        $day_blog = date("d",strtotime($date_create));
//                                        echo $day_blog;
//                                        ?>
<!--                                    </div>-->
<!--                                    <div class="month-post">-->
<!--                                        --><?php
//                                        $month_blog = date("M",strtotime($date_create));
//                                        echo $month_blog;
//                                        ?>
<!--                                    </div>-->
<!--                                    <div class="year-post">-->
<!--                                        --><?php
//                                        $year_blog = date("y",strtotime($date_create));
//                                        echo $year_blog;
//                                        ?>
<!--                                    </div>-->
                                </div>

                            </div>

                            <div class="content-latest-post">
                                <?php $text = str_replace($first_img, '', $subject);
                                //echo $text;
                                echo substr($text,0,220);
                                ?>
                            </div>
                            <div class="action-post">
                                <a class="read-more-post" href="<?php echo $post->getAddress(); ?>" title="<?php echo $this->__('Read More');?>"><?php echo $this->__('Read More');?></a>
                            </div>
                        </div>

                    </div>
                    <?php if($i == 3) break;?>
                <?php endforeach; ?>
            </div>


            <script>
                jQuery(document).ready(function($) {
                    var slider_post = $(".slider-post");
                    slider_post.owlCarousel({

                        responsive:{
                            0:{
                                items:1
                            },
                            480:{
                                items:1
                            },
                            768:{
                                items:2
                            },
                            992:{
                                items:2
                            },
                            1200:{
                                items:3
                            }
                        },

                        autoplay:false,
                        loop:false,
                        nav : false, // Show next and prev buttons
                        dots: false,
                        autoplaySpeed : 500,
                        navSpeed : 500,
                        dotsSpeed : 500,
                        autoplayHoverPause: true,
                        margin:30
                    });

                });
            </script>
        </div>
    </div>
<?php endif; ?>



