<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Blog
 * @version    1.3.6
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?>
<?php if ($posts = $this->getRecent()): ?>
<div class="latest-post-block block-column">
	<div class="title-home">
        <h2><?php echo $this->__('Our BLog') ?></h2>
    </div>
    <div class="pre-text">Lorem ipsum dolor sit amet</div>
	<div class="content-latest-post">
				<div class="slider-post">
				<?php $i = 0; foreach ($posts as $post): $i++;?>
                    <?php if(($i - 1)%2 == 0): ?>
					<div class="item">
                    <?php endif; ?>
                    <div class="item-child">

						<div class="img-post">
							<?php
								$pattern = "/<img .+\/>/";
								$subject = $post->getShortContent();
								$result = preg_match( $pattern, $subject , $matches , PREG_OFFSET_CAPTURE );
								$matched =$matches[0];
								$first_img=$matched[0];
								//print_r($first_img);
							?>
							
							<a class="img-link" title="<?php echo $post->getTitle(); ?>" href="<?php echo $post->getAddress(); ?>" ><?php echo $first_img;?></a>
						</div>
						
						<div class="info-post">
							<div class="title-latest-post">
                                <h2><a title="<?php echo $post->getTitle(); ?>" href="<?php echo $post->getAddress(); ?>" ><?php echo substr($post->getTitle(),0,25); ?></a></h2>
                                <div class="date-post">
									<?php $date_create = $post->getCreatedTime();
                                    $date_create = date("j F Y", strtotime($date_create));
                                    echo $date_create;
                                    ?>
<!--									<div class="day-post">-->
<!--										--><?php
//											$day_blog = date("d",strtotime($date_create));
//											echo $day_blog;
//										?>
<!--									</div>-->
<!--									<div class="month-post">-->
<!--										--><?php
//											$month_blog = date("M",strtotime($date_create));
//											echo $month_blog;
//										?>
<!--									</div>-->
								</div>
							</div>

							<div class="content-latest-post">
									<?php $text = str_replace($first_img, '', $subject); 
										//echo $text;
										echo substr($text,0,90);
									?>
							</div>
							<div class="action-post">
								<a class="read-more-post" href="<?php echo $post->getAddress(); ?>" title="<?php echo $this->__('Read More');?>"><?php echo $this->__('Read More');?></a>
							</div>
                        </div>
                    </div>
					<?php if($i%2 == 0 || $i == count($posts)): ?>
					</div>
                    <?php endif; ?>
				<?php endforeach; ?>
				</div>
	
			
			<script>
				jQuery(document).ready(function($) {
					var slider_post = $(".slider-post");
					slider_post.owlCarousel({

						responsive:{
							0:{
								items:1
							},
							480:{
								items:1
							},
							768:{
								items:1
							},
							992:{
								items:1
							},
							1200:{
								items:1
							}
						},
						
						autoplay:false,
						loop:false,
						nav : true, // Show next and prev buttons
						dots: false,
						autoplaySpeed : 500,
						navSpeed : 500,
						dotsSpeed : 500,
						margin:3,
						autoplayHoverPause: true

					});	 

				});	
			</script>	
	</div>
</div>
<?php endif; ?>



