<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Blog
 * @version    1.3.6
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php $posts = $this->getPosts(); ?>

<div class="block latest-post-block blog-sidebar">
    <div id="messages_product_view">
        <?php Mage::app()->getLayout()->getMessagesBlock()->setMessages(Mage::getSingleton('customer/session')->getMessages(true)); ?>
        <?php echo Mage::app()->getLayout()->getMessagesBlock()->getGroupedHtml(); ?>
    </div>

    <div class="title-home">
        <h2><?php echo $this->__('Our BLog') ?></h2>
    </div>

    <?php $i = 0; foreach ($posts as $post): ?>
        <div class="postWrapper">
            <?php
            $i++;
            $pattern = "/<img .+\/>/";
            $subject = $post->getPostContent();
            $result = preg_match( $pattern, $subject , $matches , PREG_OFFSET_CAPTURE );
            $matched =$matches[0];
            $first_img=$matched[0];
            //print_r($first_img);
            ?>

            <div class="item-post">
                <div class="date-post">
                    <div class="day-post">
                        <?php $date_create = $post->getCreatedTime();?>
                        <?php
                        $day_blog = date("d",strtotime($date_create));
                        echo $day_blog;
                        ?>
                    </div>
                    <div class="month-post">
                        <?php
                        $month_blog = date("M",strtotime($date_create));
                        echo $month_blog;
                        ?>
                    </div>
                </div>
                <div class="info-post">
                    <div class="postTitle">
                        <a href="<?php echo $post->getAddress(); ?>" ><?php   echo substr($post->getTitle(),0,25);  ?></a>
                    </div>
                    <div class="postContent">
                        <?php $text = str_replace($first_img, '', $post->getPostContent());
                        //                echo $text;
                        echo substr($text,0,80);
                        ?>
                    </div>
                </div>

            </div>

        </div>
        <?php if ($i == 3) { break;} ?>
    <?php endforeach; ?>
</div>


